name: deploy

on:
  push:
    branches: ["main"]

# Variables globales
env:
  DOCKER_REGISTRY: toposx28
  IMAGE_NAME: rest_api

jobs:
  build:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v4  # <-- CORRECCIÓN 1: Nombre correcto de la acción

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build + Push
        uses: docker/build-push-action@v5  # <-- Actualizado a v5 (recomendado)
        with:
          context: .  # <-- CORRECCIÓN 3: Indica que el Dockerfile está en la raíz
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest  # <-- CORRECCIÓN 2: Nombre de variable correcto
          build-args: |
            APP_ENV=${{ secrets.APP_ENV }}

  test:
    name: Run tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run test
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install
      - run: npm run test